### ISSUE TITLE
MacOS builds

### ISSUE THREAD

**Issue by titansmc** [e-user/50shades#3]
Hi,
would it be possible to have the MacOS packages also available? I tried the cross-compile option but it didn't work.
Thanks.

**Comment by outergod** [comment]
Hi,

the releases page contains cross-compiled release and debug binaries for MacOS which were also tested on several systems. Download the file `50shades-0.1.0-beta.0-release-x86_64-apple-darwin.gz`, gunzip and set the executable flag.
